// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: recovery.proto

package recoverypb

import (
	predict "github.com/aegis/go-services/shared/pb/predict"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActionType int32

const (
	ActionType_ACTION_TYPE_UNSPECIFIED ActionType = 0
	ActionType_RESTART                 ActionType = 1
	ActionType_SCALE_UP                ActionType = 2
	ActionType_SCALE_DOWN              ActionType = 3
	ActionType_REROUTE_TRAFFIC         ActionType = 4
	ActionType_FLUSH_CACHE             ActionType = 5
	ActionType_INCREASE_POOL           ActionType = 6
	ActionType_ISOLATE                 ActionType = 7
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0: "ACTION_TYPE_UNSPECIFIED",
		1: "RESTART",
		2: "SCALE_UP",
		3: "SCALE_DOWN",
		4: "REROUTE_TRAFFIC",
		5: "FLUSH_CACHE",
		6: "INCREASE_POOL",
		7: "ISOLATE",
	}
	ActionType_value = map[string]int32{
		"ACTION_TYPE_UNSPECIFIED": 0,
		"RESTART":                 1,
		"SCALE_UP":                2,
		"SCALE_DOWN":              3,
		"REROUTE_TRAFFIC":         4,
		"FLUSH_CACHE":             5,
		"INCREASE_POOL":           6,
		"ISOLATE":                 7,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_recovery_proto_enumTypes[0].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_recovery_proto_enumTypes[0]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_recovery_proto_rawDescGZIP(), []int{0}
}

type RecoveryAction struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ActionId       string                 `protobuf:"bytes,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	ActionType     ActionType             `protobuf:"varint,2,opt,name=action_type,json=actionType,proto3,enum=aegis.recovery.ActionType" json:"action_type,omitempty"`
	TargetNodeId   string                 `protobuf:"bytes,3,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	Parameters     map[string]string      `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExecutionOrder int32                  `protobuf:"varint,5,opt,name=execution_order,json=executionOrder,proto3" json:"execution_order,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RecoveryAction) Reset() {
	*x = RecoveryAction{}
	mi := &file_recovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoveryAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveryAction) ProtoMessage() {}

func (x *RecoveryAction) ProtoReflect() protoreflect.Message {
	mi := &file_recovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveryAction.ProtoReflect.Descriptor instead.
func (*RecoveryAction) Descriptor() ([]byte, []int) {
	return file_recovery_proto_rawDescGZIP(), []int{0}
}

func (x *RecoveryAction) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *RecoveryAction) GetActionType() ActionType {
	if x != nil {
		return x.ActionType
	}
	return ActionType_ACTION_TYPE_UNSPECIFIED
}

func (x *RecoveryAction) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

func (x *RecoveryAction) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *RecoveryAction) GetExecutionOrder() int32 {
	if x != nil {
		return x.ExecutionOrder
	}
	return 0
}

type RiskAssessment struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RiskLevel        string                 `protobuf:"bytes,1,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`
	RiskScore        float64                `protobuf:"fixed64,2,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	RequiresApproval bool                   `protobuf:"varint,3,opt,name=requires_approval,json=requiresApproval,proto3" json:"requires_approval,omitempty"`
	Justification    string                 `protobuf:"bytes,4,opt,name=justification,proto3" json:"justification,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RiskAssessment) Reset() {
	*x = RiskAssessment{}
	mi := &file_recovery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskAssessment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskAssessment) ProtoMessage() {}

func (x *RiskAssessment) ProtoReflect() protoreflect.Message {
	mi := &file_recovery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskAssessment.ProtoReflect.Descriptor instead.
func (*RiskAssessment) Descriptor() ([]byte, []int) {
	return file_recovery_proto_rawDescGZIP(), []int{1}
}

func (x *RiskAssessment) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

func (x *RiskAssessment) GetRiskScore() float64 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *RiskAssessment) GetRequiresApproval() bool {
	if x != nil {
		return x.RequiresApproval
	}
	return false
}

func (x *RiskAssessment) GetJustification() string {
	if x != nil {
		return x.Justification
	}
	return ""
}

type RecoveryPlan struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PlanId            string                 `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	Actions           []*RecoveryAction      `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
	Risk              *RiskAssessment        `protobuf:"bytes,3,opt,name=risk,proto3" json:"risk,omitempty"`
	CreatedAtUnixNano int64                  `protobuf:"varint,4,opt,name=created_at_unix_nano,json=createdAtUnixNano,proto3" json:"created_at_unix_nano,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RecoveryPlan) Reset() {
	*x = RecoveryPlan{}
	mi := &file_recovery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoveryPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveryPlan) ProtoMessage() {}

func (x *RecoveryPlan) ProtoReflect() protoreflect.Message {
	mi := &file_recovery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveryPlan.ProtoReflect.Descriptor instead.
func (*RecoveryPlan) Descriptor() ([]byte, []int) {
	return file_recovery_proto_rawDescGZIP(), []int{2}
}

func (x *RecoveryPlan) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *RecoveryPlan) GetActions() []*RecoveryAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *RecoveryPlan) GetRisk() *RiskAssessment {
	if x != nil {
		return x.Risk
	}
	return nil
}

func (x *RecoveryPlan) GetCreatedAtUnixNano() int64 {
	if x != nil {
		return x.CreatedAtUnixNano
	}
	return 0
}

type RecoveryResult struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PlanId              string                 `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	Success             bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ExecutedActionIds   []string               `protobuf:"bytes,3,rep,name=executed_action_ids,json=executedActionIds,proto3" json:"executed_action_ids,omitempty"`
	Details             string                 `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	CompletedAtUnixNano int64                  `protobuf:"varint,5,opt,name=completed_at_unix_nano,json=completedAtUnixNano,proto3" json:"completed_at_unix_nano,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RecoveryResult) Reset() {
	*x = RecoveryResult{}
	mi := &file_recovery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoveryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveryResult) ProtoMessage() {}

func (x *RecoveryResult) ProtoReflect() protoreflect.Message {
	mi := &file_recovery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveryResult.ProtoReflect.Descriptor instead.
func (*RecoveryResult) Descriptor() ([]byte, []int) {
	return file_recovery_proto_rawDescGZIP(), []int{3}
}

func (x *RecoveryResult) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *RecoveryResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RecoveryResult) GetExecutedActionIds() []string {
	if x != nil {
		return x.ExecutedActionIds
	}
	return nil
}

func (x *RecoveryResult) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *RecoveryResult) GetCompletedAtUnixNano() int64 {
	if x != nil {
		return x.CompletedAtUnixNano
	}
	return 0
}

var File_recovery_proto protoreflect.FileDescriptor

const file_recovery_proto_rawDesc = "" +
	"\n" +
	"\x0erecovery.proto\x12\x0eaegis.recovery\x1a\rpredict.proto\"\xc8\x02\n" +
	"\x0eRecoveryAction\x12\x1b\n" +
	"\taction_id\x18\x01 \x01(\tR\bactionId\x12;\n" +
	"\vaction_type\x18\x02 \x01(\x0e2\x1a.aegis.recovery.ActionTypeR\n" +
	"actionType\x12$\n" +
	"\x0etarget_node_id\x18\x03 \x01(\tR\ftargetNodeId\x12N\n" +
	"\n" +
	"parameters\x18\x04 \x03(\v2..aegis.recovery.RecoveryAction.ParametersEntryR\n" +
	"parameters\x12'\n" +
	"\x0fexecution_order\x18\x05 \x01(\x05R\x0eexecutionOrder\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa1\x01\n" +
	"\x0eRiskAssessment\x12\x1d\n" +
	"\n" +
	"risk_level\x18\x01 \x01(\tR\triskLevel\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x02 \x01(\x01R\triskScore\x12+\n" +
	"\x11requires_approval\x18\x03 \x01(\bR\x10requiresApproval\x12$\n" +
	"\rjustification\x18\x04 \x01(\tR\rjustification\"\xc6\x01\n" +
	"\fRecoveryPlan\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\tR\x06planId\x128\n" +
	"\aactions\x18\x02 \x03(\v2\x1e.aegis.recovery.RecoveryActionR\aactions\x122\n" +
	"\x04risk\x18\x03 \x01(\v2\x1e.aegis.recovery.RiskAssessmentR\x04risk\x12/\n" +
	"\x14created_at_unix_nano\x18\x04 \x01(\x03R\x11createdAtUnixNano\"\xc2\x01\n" +
	"\x0eRecoveryResult\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\tR\x06planId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12.\n" +
	"\x13executed_action_ids\x18\x03 \x03(\tR\x11executedActionIds\x12\x18\n" +
	"\adetails\x18\x04 \x01(\tR\adetails\x123\n" +
	"\x16completed_at_unix_nano\x18\x05 \x01(\x03R\x13completedAtUnixNano*\x9a\x01\n" +
	"\n" +
	"ActionType\x12\x1b\n" +
	"\x17ACTION_TYPE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aRESTART\x10\x01\x12\f\n" +
	"\bSCALE_UP\x10\x02\x12\x0e\n" +
	"\n" +
	"SCALE_DOWN\x10\x03\x12\x13\n" +
	"\x0fREROUTE_TRAFFIC\x10\x04\x12\x0f\n" +
	"\vFLUSH_CACHE\x10\x05\x12\x11\n" +
	"\rINCREASE_POOL\x10\x06\x12\v\n" +
	"\aISOLATE\x10\a2\xac\x01\n" +
	"\x0fRecoveryService\x12L\n" +
	"\fGeneratePlan\x12\x1e.aegis.predict.PredictResponse\x1a\x1c.aegis.recovery.RecoveryPlan\x12K\n" +
	"\vExecutePlan\x12\x1c.aegis.recovery.RecoveryPlan\x1a\x1e.aegis.recovery.RecoveryResultB<Z:github.com/aegis/go-services/shared/pb/recovery;recoverypbb\x06proto3"

var (
	file_recovery_proto_rawDescOnce sync.Once
	file_recovery_proto_rawDescData []byte
)

func file_recovery_proto_rawDescGZIP() []byte {
	file_recovery_proto_rawDescOnce.Do(func() {
		file_recovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recovery_proto_rawDesc), len(file_recovery_proto_rawDesc)))
	})
	return file_recovery_proto_rawDescData
}

var file_recovery_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_recovery_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_recovery_proto_goTypes = []any{
	(ActionType)(0),                 // 0: aegis.recovery.ActionType
	(*RecoveryAction)(nil),          // 1: aegis.recovery.RecoveryAction
	(*RiskAssessment)(nil),          // 2: aegis.recovery.RiskAssessment
	(*RecoveryPlan)(nil),            // 3: aegis.recovery.RecoveryPlan
	(*RecoveryResult)(nil),          // 4: aegis.recovery.RecoveryResult
	nil,                             // 5: aegis.recovery.RecoveryAction.ParametersEntry
	(*predict.PredictResponse)(nil), // 6: aegis.predict.PredictResponse
}
var file_recovery_proto_depIdxs = []int32{
	0, // 0: aegis.recovery.RecoveryAction.action_type:type_name -> aegis.recovery.ActionType
	5, // 1: aegis.recovery.RecoveryAction.parameters:type_name -> aegis.recovery.RecoveryAction.ParametersEntry
	1, // 2: aegis.recovery.RecoveryPlan.actions:type_name -> aegis.recovery.RecoveryAction
	2, // 3: aegis.recovery.RecoveryPlan.risk:type_name -> aegis.recovery.RiskAssessment
	6, // 4: aegis.recovery.RecoveryService.GeneratePlan:input_type -> aegis.predict.PredictResponse
	3, // 5: aegis.recovery.RecoveryService.ExecutePlan:input_type -> aegis.recovery.RecoveryPlan
	3, // 6: aegis.recovery.RecoveryService.GeneratePlan:output_type -> aegis.recovery.RecoveryPlan
	4, // 7: aegis.recovery.RecoveryService.ExecutePlan:output_type -> aegis.recovery.RecoveryResult
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_recovery_proto_init() }
func file_recovery_proto_init() {
	if File_recovery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recovery_proto_rawDesc), len(file_recovery_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recovery_proto_goTypes,
		DependencyIndexes: file_recovery_proto_depIdxs,
		EnumInfos:         file_recovery_proto_enumTypes,
		MessageInfos:      file_recovery_proto_msgTypes,
	}.Build()
	File_recovery_proto = out.File
	file_recovery_proto_goTypes = nil
	file_recovery_proto_depIdxs = nil
}
