// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: recovery.proto

package recoverypb

import (
	context "context"
	predict "github.com/aegis/go-services/shared/pb/predict"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RecoveryService_GeneratePlan_FullMethodName = "/aegis.recovery.RecoveryService/GeneratePlan"
	RecoveryService_ExecutePlan_FullMethodName  = "/aegis.recovery.RecoveryService/ExecutePlan"
)

// RecoveryServiceClient is the client API for RecoveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecoveryServiceClient interface {
	GeneratePlan(ctx context.Context, in *predict.PredictResponse, opts ...grpc.CallOption) (*RecoveryPlan, error)
	ExecutePlan(ctx context.Context, in *RecoveryPlan, opts ...grpc.CallOption) (*RecoveryResult, error)
}

type recoveryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRecoveryServiceClient(cc grpc.ClientConnInterface) RecoveryServiceClient {
	return &recoveryServiceClient{cc}
}

func (c *recoveryServiceClient) GeneratePlan(ctx context.Context, in *predict.PredictResponse, opts ...grpc.CallOption) (*RecoveryPlan, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecoveryPlan)
	err := c.cc.Invoke(ctx, RecoveryService_GeneratePlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recoveryServiceClient) ExecutePlan(ctx context.Context, in *RecoveryPlan, opts ...grpc.CallOption) (*RecoveryResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecoveryResult)
	err := c.cc.Invoke(ctx, RecoveryService_ExecutePlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecoveryServiceServer is the server API for RecoveryService service.
// All implementations must embed UnimplementedRecoveryServiceServer
// for forward compatibility.
type RecoveryServiceServer interface {
	GeneratePlan(context.Context, *predict.PredictResponse) (*RecoveryPlan, error)
	ExecutePlan(context.Context, *RecoveryPlan) (*RecoveryResult, error)
	mustEmbedUnimplementedRecoveryServiceServer()
}

// UnimplementedRecoveryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecoveryServiceServer struct{}

func (UnimplementedRecoveryServiceServer) GeneratePlan(context.Context, *predict.PredictResponse) (*RecoveryPlan, error) {
	return nil, status.Error(codes.Unimplemented, "method GeneratePlan not implemented")
}
func (UnimplementedRecoveryServiceServer) ExecutePlan(context.Context, *RecoveryPlan) (*RecoveryResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecutePlan not implemented")
}
func (UnimplementedRecoveryServiceServer) mustEmbedUnimplementedRecoveryServiceServer() {}
func (UnimplementedRecoveryServiceServer) testEmbeddedByValue()                         {}

// UnsafeRecoveryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecoveryServiceServer will
// result in compilation errors.
type UnsafeRecoveryServiceServer interface {
	mustEmbedUnimplementedRecoveryServiceServer()
}

func RegisterRecoveryServiceServer(s grpc.ServiceRegistrar, srv RecoveryServiceServer) {
	// If the following call panics, it indicates UnimplementedRecoveryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RecoveryService_ServiceDesc, srv)
}

func _RecoveryService_GeneratePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(predict.PredictResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecoveryServiceServer).GeneratePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecoveryService_GeneratePlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecoveryServiceServer).GeneratePlan(ctx, req.(*predict.PredictResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecoveryService_ExecutePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecoveryPlan)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecoveryServiceServer).ExecutePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecoveryService_ExecutePlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecoveryServiceServer).ExecutePlan(ctx, req.(*RecoveryPlan))
	}
	return interceptor(ctx, in, info, handler)
}

// RecoveryService_ServiceDesc is the grpc.ServiceDesc for RecoveryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecoveryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aegis.recovery.RecoveryService",
	HandlerType: (*RecoveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GeneratePlan",
			Handler:    _RecoveryService_GeneratePlan_Handler,
		},
		{
			MethodName: "ExecutePlan",
			Handler:    _RecoveryService_ExecutePlan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recovery.proto",
}
