# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: graph.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'graph.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgraph.proto\x12\x0b\x61\x65gis.graph\"\x83\x02\n\x04Node\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x31\n\x08metadata\x18\x05 \x03(\x0b\x32\x1f.aegis.graph.Node.MetadataEntry\x12/\n\x07metrics\x18\x06 \x03(\x0b\x32\x1e.aegis.graph.Node.MetricsEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a.\n\x0cMetricsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\"x\n\x04\x45\x64ge\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x0e\n\x06target\x18\x02 \x01(\t\x12\x14\n\x0crelationship\x18\x03 \x01(\t\x12\x12\n\nlatency_ms\x18\x04 \x01(\x01\x12\x12\n\nerror_rate\x18\x05 \x01(\x01\x12\x12\n\nthroughput\x18\x06 \x01(\x01\"p\n\rGraphSnapshot\x12\x1b\n\x13timestamp_unix_nano\x18\x01 \x01(\x03\x12 \n\x05nodes\x18\x02 \x03(\x0b\x32\x11.aegis.graph.Node\x12 \n\x05\x65\x64ges\x18\x03 \x03(\x0b\x32\x11.aegis.graph.Edge\"D\n\x1aStronglyConnectedComponent\x12\x14\n\x0c\x63omponent_id\x18\x01 \x01(\t\x12\x10\n\x08node_ids\x18\x02 \x03(\t\"\xc3\x02\n\x13GraphRepresentation\x12,\n\x08snapshot\x18\x01 \x01(\x0b\x32\x1a.aegis.graph.GraphSnapshot\x12\x19\n\x11topological_order\x18\x02 \x03(\t\x12Q\n\x11\x63\x65ntrality_scores\x18\x03 \x03(\x0b\x32\x36.aegis.graph.GraphRepresentation.CentralityScoresEntry\x12?\n\x0escc_components\x18\x04 \x03(\x0b\x32\'.aegis.graph.StronglyConnectedComponent\x12\x16\n\x0e\x66\x65\x61ture_tensor\x18\x05 \x01(\x0c\x1a\x37\n\x15\x43\x65ntralityScoresEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\x42\x36Z4github.com/aegis/go-services/shared/pb/graph;graphpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'graph_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z4github.com/aegis/go-services/shared/pb/graph;graphpb'
  _globals['_NODE_METADATAENTRY']._loaded_options = None
  _globals['_NODE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_NODE_METRICSENTRY']._loaded_options = None
  _globals['_NODE_METRICSENTRY']._serialized_options = b'8\001'
  _globals['_GRAPHREPRESENTATION_CENTRALITYSCORESENTRY']._loaded_options = None
  _globals['_GRAPHREPRESENTATION_CENTRALITYSCORESENTRY']._serialized_options = b'8\001'
  _globals['_NODE']._serialized_start=29
  _globals['_NODE']._serialized_end=288
  _globals['_NODE_METADATAENTRY']._serialized_start=193
  _globals['_NODE_METADATAENTRY']._serialized_end=240
  _globals['_NODE_METRICSENTRY']._serialized_start=242
  _globals['_NODE_METRICSENTRY']._serialized_end=288
  _globals['_EDGE']._serialized_start=290
  _globals['_EDGE']._serialized_end=410
  _globals['_GRAPHSNAPSHOT']._serialized_start=412
  _globals['_GRAPHSNAPSHOT']._serialized_end=524
  _globals['_STRONGLYCONNECTEDCOMPONENT']._serialized_start=526
  _globals['_STRONGLYCONNECTEDCOMPONENT']._serialized_end=594
  _globals['_GRAPHREPRESENTATION']._serialized_start=597
  _globals['_GRAPHREPRESENTATION']._serialized_end=920
  _globals['_GRAPHREPRESENTATION_CENTRALITYSCORESENTRY']._serialized_start=865
  _globals['_GRAPHREPRESENTATION_CENTRALITYSCORESENTRY']._serialized_end=920
# @@protoc_insertion_point(module_scope)
