# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: predict.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'predict.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import graph_pb2 as graph__pb2
import telemetry_pb2 as telemetry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpredict.proto\x12\raegis.predict\x1a\x0bgraph.proto\x1a\x0ftelemetry.proto\"|\n\x11\x46\x61ilurePrediction\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x1b\n\x13\x66\x61ilure_probability\x18\x02 \x01(\x01\x12\x12\n\nconfidence\x18\x03 \x01(\x01\x12%\n\x1d\x65stimated_time_to_failure_sec\x18\x04 \x01(\x03\"d\n\tRootCause\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x13\n\x0bprobability\x18\x02 \x01(\x01\x12\x13\n\x0b\x65xplanation\x18\x03 \x01(\t\x12\x1c\n\x14\x63ontributing_metrics\x18\x04 \x03(\t\"?\n\x0fPropagationPath\x12\x12\n\npath_nodes\x18\x01 \x03(\t\x12\x18\n\x10propagation_risk\x18\x02 \x01(\x01\"\x94\x01\n\x0ePredictRequest\x12/\n\x05graph\x18\x01 \x01(\x0b\x32 .aegis.graph.GraphRepresentation\x12\x39\n\x10recent_telemetry\x18\x02 \x01(\x0b\x32\x1f.aegis.telemetry.TelemetryBatch\x12\x16\n\x0etarget_node_id\x18\x03 \x01(\t\"\xd7\x01\n\x0fPredictResponse\x12=\n\x13\x66\x61ilure_predictions\x18\x01 \x03(\x0b\x32 .aegis.predict.FailurePrediction\x12-\n\x0broot_causes\x18\x02 \x03(\x0b\x32\x18.aegis.predict.RootCause\x12\x39\n\x11propagation_paths\x18\x03 \x03(\x0b\x32\x1e.aegis.predict.PropagationPath\x12\x1b\n\x13timestamp_unix_nano\x18\x04 \x01(\x03\x32]\n\x11PredictionService\x12H\n\x07Predict\x12\x1d.aegis.predict.PredictRequest\x1a\x1e.aegis.predict.PredictResponseB:Z8github.com/aegis/go-services/shared/pb/predict;predictpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'predict_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8github.com/aegis/go-services/shared/pb/predict;predictpb'
  _globals['_FAILUREPREDICTION']._serialized_start=62
  _globals['_FAILUREPREDICTION']._serialized_end=186
  _globals['_ROOTCAUSE']._serialized_start=188
  _globals['_ROOTCAUSE']._serialized_end=288
  _globals['_PROPAGATIONPATH']._serialized_start=290
  _globals['_PROPAGATIONPATH']._serialized_end=353
  _globals['_PREDICTREQUEST']._serialized_start=356
  _globals['_PREDICTREQUEST']._serialized_end=504
  _globals['_PREDICTRESPONSE']._serialized_start=507
  _globals['_PREDICTRESPONSE']._serialized_end=722
  _globals['_PREDICTIONSERVICE']._serialized_start=724
  _globals['_PREDICTIONSERVICE']._serialized_end=817
# @@protoc_insertion_point(module_scope)
