# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recovery.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'recovery.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import predict_pb2 as predict__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0erecovery.proto\x12\x0e\x61\x65gis.recovery\x1a\rpredict.proto\"\xfc\x01\n\x0eRecoveryAction\x12\x11\n\taction_id\x18\x01 \x01(\t\x12/\n\x0b\x61\x63tion_type\x18\x02 \x01(\x0e\x32\x1a.aegis.recovery.ActionType\x12\x16\n\x0etarget_node_id\x18\x03 \x01(\t\x12\x42\n\nparameters\x18\x04 \x03(\x0b\x32..aegis.recovery.RecoveryAction.ParametersEntry\x12\x17\n\x0f\x65xecution_order\x18\x05 \x01(\x05\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"j\n\x0eRiskAssessment\x12\x12\n\nrisk_level\x18\x01 \x01(\t\x12\x12\n\nrisk_score\x18\x02 \x01(\x01\x12\x19\n\x11requires_approval\x18\x03 \x01(\x08\x12\x15\n\rjustification\x18\x04 \x01(\t\"\x9c\x01\n\x0cRecoveryPlan\x12\x0f\n\x07plan_id\x18\x01 \x01(\t\x12/\n\x07\x61\x63tions\x18\x02 \x03(\x0b\x32\x1e.aegis.recovery.RecoveryAction\x12,\n\x04risk\x18\x03 \x01(\x0b\x32\x1e.aegis.recovery.RiskAssessment\x12\x1c\n\x14\x63reated_at_unix_nano\x18\x04 \x01(\x03\"\x80\x01\n\x0eRecoveryResult\x12\x0f\n\x07plan_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x1b\n\x13\x65xecuted_action_ids\x18\x03 \x03(\t\x12\x0f\n\x07\x64\x65tails\x18\x04 \x01(\t\x12\x1e\n\x16\x63ompleted_at_unix_nano\x18\x05 \x01(\x03*\x9a\x01\n\nActionType\x12\x1b\n\x17\x41\x43TION_TYPE_UNSPECIFIED\x10\x00\x12\x0b\n\x07RESTART\x10\x01\x12\x0c\n\x08SCALE_UP\x10\x02\x12\x0e\n\nSCALE_DOWN\x10\x03\x12\x13\n\x0fREROUTE_TRAFFIC\x10\x04\x12\x0f\n\x0b\x46LUSH_CACHE\x10\x05\x12\x11\n\rINCREASE_POOL\x10\x06\x12\x0b\n\x07ISOLATE\x10\x07\x32\xac\x01\n\x0fRecoveryService\x12L\n\x0cGeneratePlan\x12\x1e.aegis.predict.PredictResponse\x1a\x1c.aegis.recovery.RecoveryPlan\x12K\n\x0b\x45xecutePlan\x12\x1c.aegis.recovery.RecoveryPlan\x1a\x1e.aegis.recovery.RecoveryResultB<Z:github.com/aegis/go-services/shared/pb/recovery;recoverypbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recovery_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z:github.com/aegis/go-services/shared/pb/recovery;recoverypb'
  _globals['_RECOVERYACTION_PARAMETERSENTRY']._loaded_options = None
  _globals['_RECOVERYACTION_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_ACTIONTYPE']._serialized_start=703
  _globals['_ACTIONTYPE']._serialized_end=857
  _globals['_RECOVERYACTION']._serialized_start=50
  _globals['_RECOVERYACTION']._serialized_end=302
  _globals['_RECOVERYACTION_PARAMETERSENTRY']._serialized_start=253
  _globals['_RECOVERYACTION_PARAMETERSENTRY']._serialized_end=302
  _globals['_RISKASSESSMENT']._serialized_start=304
  _globals['_RISKASSESSMENT']._serialized_end=410
  _globals['_RECOVERYPLAN']._serialized_start=413
  _globals['_RECOVERYPLAN']._serialized_end=569
  _globals['_RECOVERYRESULT']._serialized_start=572
  _globals['_RECOVERYRESULT']._serialized_end=700
  _globals['_RECOVERYSERVICE']._serialized_start=860
  _globals['_RECOVERYSERVICE']._serialized_end=1032
# @@protoc_insertion_point(module_scope)
