# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\x0f\x61\x65gis.telemetry\"\xdf\x01\n\x08LogEntry\x12\x1b\n\x13timestamp_unix_nano\x18\x01 \x01(\x03\x12\x12\n\nservice_id\x18\x02 \x01(\t\x12\r\n\x05level\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\x12\x10\n\x08trace_id\x18\x05 \x01(\t\x12=\n\nattributes\x18\x06 \x03(\x0b\x32).aegis.telemetry.LogEntry.AttributesEntry\x1a\x31\n\x0f\x41ttributesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xd9\x01\n\x0bMetricPoint\x12\x1b\n\x13timestamp_unix_nano\x18\x01 \x01(\x03\x12\x12\n\nservice_id\x18\x02 \x01(\t\x12\x13\n\x0bmetric_name\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\x01\x12\x0c\n\x04unit\x18\x05 \x01(\t\x12\x38\n\x06labels\x18\x06 \x03(\x0b\x32(.aegis.telemetry.MetricPoint.LabelsEntry\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xb4\x02\n\tTraceSpan\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x0f\n\x07span_id\x18\x02 \x01(\t\x12\x16\n\x0eparent_span_id\x18\x03 \x01(\t\x12\x12\n\nservice_id\x18\x04 \x01(\t\x12\x16\n\x0eoperation_name\x18\x05 \x01(\t\x12\x1c\n\x14start_time_unix_nano\x18\x06 \x01(\x03\x12\x1a\n\x12\x65nd_time_unix_nano\x18\x07 \x01(\x03\x12\x13\n\x0bstatus_code\x18\x08 \x01(\x05\x12>\n\nattributes\x18\t \x03(\x0b\x32*.aegis.telemetry.TraceSpan.AttributesEntry\x1a\x31\n\x0f\x41ttributesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x94\x01\n\x0eTelemetryBatch\x12\'\n\x04logs\x18\x01 \x03(\x0b\x32\x19.aegis.telemetry.LogEntry\x12-\n\x07metrics\x18\x02 \x03(\x0b\x32\x1c.aegis.telemetry.MetricPoint\x12*\n\x06traces\x18\x03 \x03(\x0b\x32\x1a.aegis.telemetry.TraceSpanB>Z<github.com/aegis/go-services/shared/pb/telemetry;telemetrypbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z<github.com/aegis/go-services/shared/pb/telemetry;telemetrypb'
  _globals['_LOGENTRY_ATTRIBUTESENTRY']._loaded_options = None
  _globals['_LOGENTRY_ATTRIBUTESENTRY']._serialized_options = b'8\001'
  _globals['_METRICPOINT_LABELSENTRY']._loaded_options = None
  _globals['_METRICPOINT_LABELSENTRY']._serialized_options = b'8\001'
  _globals['_TRACESPAN_ATTRIBUTESENTRY']._loaded_options = None
  _globals['_TRACESPAN_ATTRIBUTESENTRY']._serialized_options = b'8\001'
  _globals['_LOGENTRY']._serialized_start=37
  _globals['_LOGENTRY']._serialized_end=260
  _globals['_LOGENTRY_ATTRIBUTESENTRY']._serialized_start=211
  _globals['_LOGENTRY_ATTRIBUTESENTRY']._serialized_end=260
  _globals['_METRICPOINT']._serialized_start=263
  _globals['_METRICPOINT']._serialized_end=480
  _globals['_METRICPOINT_LABELSENTRY']._serialized_start=435
  _globals['_METRICPOINT_LABELSENTRY']._serialized_end=480
  _globals['_TRACESPAN']._serialized_start=483
  _globals['_TRACESPAN']._serialized_end=791
  _globals['_TRACESPAN_ATTRIBUTESENTRY']._serialized_start=211
  _globals['_TRACESPAN_ATTRIBUTESENTRY']._serialized_end=260
  _globals['_TELEMETRYBATCH']._serialized_start=794
  _globals['_TELEMETRYBATCH']._serialized_end=942
# @@protoc_insertion_point(module_scope)
