// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: telemetry.proto

package telemetrypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogEntry struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TimestampUnixNano int64                  `protobuf:"varint,1,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`
	ServiceId         string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Level             string                 `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	Message           string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	TraceId           string                 `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Attributes        map[string]string      `protobuf:"bytes,6,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntry) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

func (x *LogEntry) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *LogEntry) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type MetricPoint struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TimestampUnixNano int64                  `protobuf:"varint,1,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`
	ServiceId         string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	MetricName        string                 `protobuf:"bytes,3,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	Value             float64                `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	Unit              string                 `protobuf:"bytes,5,opt,name=unit,proto3" json:"unit,omitempty"`
	Labels            map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MetricPoint) Reset() {
	*x = MetricPoint{}
	mi := &file_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricPoint) ProtoMessage() {}

func (x *MetricPoint) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricPoint.ProtoReflect.Descriptor instead.
func (*MetricPoint) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *MetricPoint) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

func (x *MetricPoint) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *MetricPoint) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *MetricPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MetricPoint) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *MetricPoint) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type TraceSpan struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TraceId           string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId            string                 `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	ParentSpanId      string                 `protobuf:"bytes,3,opt,name=parent_span_id,json=parentSpanId,proto3" json:"parent_span_id,omitempty"`
	ServiceId         string                 `protobuf:"bytes,4,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	OperationName     string                 `protobuf:"bytes,5,opt,name=operation_name,json=operationName,proto3" json:"operation_name,omitempty"`
	StartTimeUnixNano int64                  `protobuf:"varint,6,opt,name=start_time_unix_nano,json=startTimeUnixNano,proto3" json:"start_time_unix_nano,omitempty"`
	EndTimeUnixNano   int64                  `protobuf:"varint,7,opt,name=end_time_unix_nano,json=endTimeUnixNano,proto3" json:"end_time_unix_nano,omitempty"`
	StatusCode        int32                  `protobuf:"varint,8,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Attributes        map[string]string      `protobuf:"bytes,9,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TraceSpan) Reset() {
	*x = TraceSpan{}
	mi := &file_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceSpan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceSpan) ProtoMessage() {}

func (x *TraceSpan) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceSpan.ProtoReflect.Descriptor instead.
func (*TraceSpan) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *TraceSpan) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *TraceSpan) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *TraceSpan) GetParentSpanId() string {
	if x != nil {
		return x.ParentSpanId
	}
	return ""
}

func (x *TraceSpan) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *TraceSpan) GetOperationName() string {
	if x != nil {
		return x.OperationName
	}
	return ""
}

func (x *TraceSpan) GetStartTimeUnixNano() int64 {
	if x != nil {
		return x.StartTimeUnixNano
	}
	return 0
}

func (x *TraceSpan) GetEndTimeUnixNano() int64 {
	if x != nil {
		return x.EndTimeUnixNano
	}
	return 0
}

func (x *TraceSpan) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *TraceSpan) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type TelemetryBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*LogEntry            `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	Metrics       []*MetricPoint         `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty"`
	Traces        []*TraceSpan           `protobuf:"bytes,3,rep,name=traces,proto3" json:"traces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryBatch) Reset() {
	*x = TelemetryBatch{}
	mi := &file_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryBatch) ProtoMessage() {}

func (x *TelemetryBatch) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryBatch.ProtoReflect.Descriptor instead.
func (*TelemetryBatch) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *TelemetryBatch) GetLogs() []*LogEntry {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *TelemetryBatch) GetMetrics() []*MetricPoint {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *TelemetryBatch) GetTraces() []*TraceSpan {
	if x != nil {
		return x.Traces
	}
	return nil
}

var File_telemetry_proto protoreflect.FileDescriptor

const file_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x0ftelemetry.proto\x12\x0faegis.telemetry\"\xae\x02\n" +
	"\bLogEntry\x12.\n" +
	"\x13timestamp_unix_nano\x18\x01 \x01(\x03R\x11timestampUnixNano\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\x12I\n" +
	"\n" +
	"attributes\x18\x06 \x03(\v2).aegis.telemetry.LogEntry.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa4\x02\n" +
	"\vMetricPoint\x12.\n" +
	"\x13timestamp_unix_nano\x18\x01 \x01(\x03R\x11timestampUnixNano\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\x12\x1f\n" +
	"\vmetric_name\x18\x03 \x01(\tR\n" +
	"metricName\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x01R\x05value\x12\x12\n" +
	"\x04unit\x18\x05 \x01(\tR\x04unit\x12@\n" +
	"\x06labels\x18\x06 \x03(\v2(.aegis.telemetry.MetricPoint.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb5\x03\n" +
	"\tTraceSpan\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x02 \x01(\tR\x06spanId\x12$\n" +
	"\x0eparent_span_id\x18\x03 \x01(\tR\fparentSpanId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x04 \x01(\tR\tserviceId\x12%\n" +
	"\x0eoperation_name\x18\x05 \x01(\tR\roperationName\x12/\n" +
	"\x14start_time_unix_nano\x18\x06 \x01(\x03R\x11startTimeUnixNano\x12+\n" +
	"\x12end_time_unix_nano\x18\a \x01(\x03R\x0fendTimeUnixNano\x12\x1f\n" +
	"\vstatus_code\x18\b \x01(\x05R\n" +
	"statusCode\x12J\n" +
	"\n" +
	"attributes\x18\t \x03(\v2*.aegis.telemetry.TraceSpan.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xab\x01\n" +
	"\x0eTelemetryBatch\x12-\n" +
	"\x04logs\x18\x01 \x03(\v2\x19.aegis.telemetry.LogEntryR\x04logs\x126\n" +
	"\ametrics\x18\x02 \x03(\v2\x1c.aegis.telemetry.MetricPointR\ametrics\x122\n" +
	"\x06traces\x18\x03 \x03(\v2\x1a.aegis.telemetry.TraceSpanR\x06tracesB>Z<github.com/aegis/go-services/shared/pb/telemetry;telemetrypbb\x06proto3"

var (
	file_telemetry_proto_rawDescOnce sync.Once
	file_telemetry_proto_rawDescData []byte
)

func file_telemetry_proto_rawDescGZIP() []byte {
	file_telemetry_proto_rawDescOnce.Do(func() {
		file_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telemetry_proto_rawDesc), len(file_telemetry_proto_rawDesc)))
	})
	return file_telemetry_proto_rawDescData
}

var file_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_telemetry_proto_goTypes = []any{
	(*LogEntry)(nil),       // 0: aegis.telemetry.LogEntry
	(*MetricPoint)(nil),    // 1: aegis.telemetry.MetricPoint
	(*TraceSpan)(nil),      // 2: aegis.telemetry.TraceSpan
	(*TelemetryBatch)(nil), // 3: aegis.telemetry.TelemetryBatch
	nil,                    // 4: aegis.telemetry.LogEntry.AttributesEntry
	nil,                    // 5: aegis.telemetry.MetricPoint.LabelsEntry
	nil,                    // 6: aegis.telemetry.TraceSpan.AttributesEntry
}
var file_telemetry_proto_depIdxs = []int32{
	4, // 0: aegis.telemetry.LogEntry.attributes:type_name -> aegis.telemetry.LogEntry.AttributesEntry
	5, // 1: aegis.telemetry.MetricPoint.labels:type_name -> aegis.telemetry.MetricPoint.LabelsEntry
	6, // 2: aegis.telemetry.TraceSpan.attributes:type_name -> aegis.telemetry.TraceSpan.AttributesEntry
	0, // 3: aegis.telemetry.TelemetryBatch.logs:type_name -> aegis.telemetry.LogEntry
	1, // 4: aegis.telemetry.TelemetryBatch.metrics:type_name -> aegis.telemetry.MetricPoint
	2, // 5: aegis.telemetry.TelemetryBatch.traces:type_name -> aegis.telemetry.TraceSpan
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_telemetry_proto_init() }
func file_telemetry_proto_init() {
	if File_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telemetry_proto_rawDesc), len(file_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_telemetry_proto_goTypes,
		DependencyIndexes: file_telemetry_proto_depIdxs,
		MessageInfos:      file_telemetry_proto_msgTypes,
	}.Build()
	File_telemetry_proto = out.File
	file_telemetry_proto_goTypes = nil
	file_telemetry_proto_depIdxs = nil
}
