// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: predict.proto

package predictpb

import (
	graph "github.com/aegis/go-services/shared/pb/graph"
	telemetry "github.com/aegis/go-services/shared/pb/telemetry"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FailurePrediction struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	NodeId                    string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	FailureProbability        float64                `protobuf:"fixed64,2,opt,name=failure_probability,json=failureProbability,proto3" json:"failure_probability,omitempty"`
	Confidence                float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	EstimatedTimeToFailureSec int64                  `protobuf:"varint,4,opt,name=estimated_time_to_failure_sec,json=estimatedTimeToFailureSec,proto3" json:"estimated_time_to_failure_sec,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *FailurePrediction) Reset() {
	*x = FailurePrediction{}
	mi := &file_predict_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailurePrediction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailurePrediction) ProtoMessage() {}

func (x *FailurePrediction) ProtoReflect() protoreflect.Message {
	mi := &file_predict_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailurePrediction.ProtoReflect.Descriptor instead.
func (*FailurePrediction) Descriptor() ([]byte, []int) {
	return file_predict_proto_rawDescGZIP(), []int{0}
}

func (x *FailurePrediction) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *FailurePrediction) GetFailureProbability() float64 {
	if x != nil {
		return x.FailureProbability
	}
	return 0
}

func (x *FailurePrediction) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *FailurePrediction) GetEstimatedTimeToFailureSec() int64 {
	if x != nil {
		return x.EstimatedTimeToFailureSec
	}
	return 0
}

type RootCause struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	NodeId              string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Probability         float64                `protobuf:"fixed64,2,opt,name=probability,proto3" json:"probability,omitempty"`
	Explanation         string                 `protobuf:"bytes,3,opt,name=explanation,proto3" json:"explanation,omitempty"`
	ContributingMetrics []string               `protobuf:"bytes,4,rep,name=contributing_metrics,json=contributingMetrics,proto3" json:"contributing_metrics,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RootCause) Reset() {
	*x = RootCause{}
	mi := &file_predict_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootCause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootCause) ProtoMessage() {}

func (x *RootCause) ProtoReflect() protoreflect.Message {
	mi := &file_predict_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootCause.ProtoReflect.Descriptor instead.
func (*RootCause) Descriptor() ([]byte, []int) {
	return file_predict_proto_rawDescGZIP(), []int{1}
}

func (x *RootCause) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RootCause) GetProbability() float64 {
	if x != nil {
		return x.Probability
	}
	return 0
}

func (x *RootCause) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *RootCause) GetContributingMetrics() []string {
	if x != nil {
		return x.ContributingMetrics
	}
	return nil
}

type PropagationPath struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PathNodes       []string               `protobuf:"bytes,1,rep,name=path_nodes,json=pathNodes,proto3" json:"path_nodes,omitempty"`
	PropagationRisk float64                `protobuf:"fixed64,2,opt,name=propagation_risk,json=propagationRisk,proto3" json:"propagation_risk,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PropagationPath) Reset() {
	*x = PropagationPath{}
	mi := &file_predict_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropagationPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropagationPath) ProtoMessage() {}

func (x *PropagationPath) ProtoReflect() protoreflect.Message {
	mi := &file_predict_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropagationPath.ProtoReflect.Descriptor instead.
func (*PropagationPath) Descriptor() ([]byte, []int) {
	return file_predict_proto_rawDescGZIP(), []int{2}
}

func (x *PropagationPath) GetPathNodes() []string {
	if x != nil {
		return x.PathNodes
	}
	return nil
}

func (x *PropagationPath) GetPropagationRisk() float64 {
	if x != nil {
		return x.PropagationRisk
	}
	return 0
}

type PredictRequest struct {
	state           protoimpl.MessageState     `protogen:"open.v1"`
	Graph           *graph.GraphRepresentation `protobuf:"bytes,1,opt,name=graph,proto3" json:"graph,omitempty"`
	RecentTelemetry *telemetry.TelemetryBatch  `protobuf:"bytes,2,opt,name=recent_telemetry,json=recentTelemetry,proto3" json:"recent_telemetry,omitempty"`
	TargetNodeId    string                     `protobuf:"bytes,3,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PredictRequest) Reset() {
	*x = PredictRequest{}
	mi := &file_predict_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictRequest) ProtoMessage() {}

func (x *PredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_predict_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictRequest.ProtoReflect.Descriptor instead.
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return file_predict_proto_rawDescGZIP(), []int{3}
}

func (x *PredictRequest) GetGraph() *graph.GraphRepresentation {
	if x != nil {
		return x.Graph
	}
	return nil
}

func (x *PredictRequest) GetRecentTelemetry() *telemetry.TelemetryBatch {
	if x != nil {
		return x.RecentTelemetry
	}
	return nil
}

func (x *PredictRequest) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

type PredictResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	FailurePredictions []*FailurePrediction   `protobuf:"bytes,1,rep,name=failure_predictions,json=failurePredictions,proto3" json:"failure_predictions,omitempty"`
	RootCauses         []*RootCause           `protobuf:"bytes,2,rep,name=root_causes,json=rootCauses,proto3" json:"root_causes,omitempty"`
	PropagationPaths   []*PropagationPath     `protobuf:"bytes,3,rep,name=propagation_paths,json=propagationPaths,proto3" json:"propagation_paths,omitempty"`
	TimestampUnixNano  int64                  `protobuf:"varint,4,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PredictResponse) Reset() {
	*x = PredictResponse{}
	mi := &file_predict_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictResponse) ProtoMessage() {}

func (x *PredictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_predict_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictResponse.ProtoReflect.Descriptor instead.
func (*PredictResponse) Descriptor() ([]byte, []int) {
	return file_predict_proto_rawDescGZIP(), []int{4}
}

func (x *PredictResponse) GetFailurePredictions() []*FailurePrediction {
	if x != nil {
		return x.FailurePredictions
	}
	return nil
}

func (x *PredictResponse) GetRootCauses() []*RootCause {
	if x != nil {
		return x.RootCauses
	}
	return nil
}

func (x *PredictResponse) GetPropagationPaths() []*PropagationPath {
	if x != nil {
		return x.PropagationPaths
	}
	return nil
}

func (x *PredictResponse) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

var File_predict_proto protoreflect.FileDescriptor

const file_predict_proto_rawDesc = "" +
	"\n" +
	"\rpredict.proto\x12\raegis.predict\x1a\vgraph.proto\x1a\x0ftelemetry.proto\"\xbf\x01\n" +
	"\x11FailurePrediction\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12/\n" +
	"\x13failure_probability\x18\x02 \x01(\x01R\x12failureProbability\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x12@\n" +
	"\x1destimated_time_to_failure_sec\x18\x04 \x01(\x03R\x19estimatedTimeToFailureSec\"\x9b\x01\n" +
	"\tRootCause\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12 \n" +
	"\vprobability\x18\x02 \x01(\x01R\vprobability\x12 \n" +
	"\vexplanation\x18\x03 \x01(\tR\vexplanation\x121\n" +
	"\x14contributing_metrics\x18\x04 \x03(\tR\x13contributingMetrics\"[\n" +
	"\x0fPropagationPath\x12\x1d\n" +
	"\n" +
	"path_nodes\x18\x01 \x03(\tR\tpathNodes\x12)\n" +
	"\x10propagation_risk\x18\x02 \x01(\x01R\x0fpropagationRisk\"\xba\x01\n" +
	"\x0ePredictRequest\x126\n" +
	"\x05graph\x18\x01 \x01(\v2 .aegis.graph.GraphRepresentationR\x05graph\x12J\n" +
	"\x10recent_telemetry\x18\x02 \x01(\v2\x1f.aegis.telemetry.TelemetryBatchR\x0frecentTelemetry\x12$\n" +
	"\x0etarget_node_id\x18\x03 \x01(\tR\ftargetNodeId\"\x9c\x02\n" +
	"\x0fPredictResponse\x12Q\n" +
	"\x13failure_predictions\x18\x01 \x03(\v2 .aegis.predict.FailurePredictionR\x12failurePredictions\x129\n" +
	"\vroot_causes\x18\x02 \x03(\v2\x18.aegis.predict.RootCauseR\n" +
	"rootCauses\x12K\n" +
	"\x11propagation_paths\x18\x03 \x03(\v2\x1e.aegis.predict.PropagationPathR\x10propagationPaths\x12.\n" +
	"\x13timestamp_unix_nano\x18\x04 \x01(\x03R\x11timestampUnixNano2]\n" +
	"\x11PredictionService\x12H\n" +
	"\aPredict\x12\x1d.aegis.predict.PredictRequest\x1a\x1e.aegis.predict.PredictResponseB:Z8github.com/aegis/go-services/shared/pb/predict;predictpbb\x06proto3"

var (
	file_predict_proto_rawDescOnce sync.Once
	file_predict_proto_rawDescData []byte
)

func file_predict_proto_rawDescGZIP() []byte {
	file_predict_proto_rawDescOnce.Do(func() {
		file_predict_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_predict_proto_rawDesc), len(file_predict_proto_rawDesc)))
	})
	return file_predict_proto_rawDescData
}

var file_predict_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_predict_proto_goTypes = []any{
	(*FailurePrediction)(nil),         // 0: aegis.predict.FailurePrediction
	(*RootCause)(nil),                 // 1: aegis.predict.RootCause
	(*PropagationPath)(nil),           // 2: aegis.predict.PropagationPath
	(*PredictRequest)(nil),            // 3: aegis.predict.PredictRequest
	(*PredictResponse)(nil),           // 4: aegis.predict.PredictResponse
	(*graph.GraphRepresentation)(nil), // 5: aegis.graph.GraphRepresentation
	(*telemetry.TelemetryBatch)(nil),  // 6: aegis.telemetry.TelemetryBatch
}
var file_predict_proto_depIdxs = []int32{
	5, // 0: aegis.predict.PredictRequest.graph:type_name -> aegis.graph.GraphRepresentation
	6, // 1: aegis.predict.PredictRequest.recent_telemetry:type_name -> aegis.telemetry.TelemetryBatch
	0, // 2: aegis.predict.PredictResponse.failure_predictions:type_name -> aegis.predict.FailurePrediction
	1, // 3: aegis.predict.PredictResponse.root_causes:type_name -> aegis.predict.RootCause
	2, // 4: aegis.predict.PredictResponse.propagation_paths:type_name -> aegis.predict.PropagationPath
	3, // 5: aegis.predict.PredictionService.Predict:input_type -> aegis.predict.PredictRequest
	4, // 6: aegis.predict.PredictionService.Predict:output_type -> aegis.predict.PredictResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_predict_proto_init() }
func file_predict_proto_init() {
	if File_predict_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_predict_proto_rawDesc), len(file_predict_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_predict_proto_goTypes,
		DependencyIndexes: file_predict_proto_depIdxs,
		MessageInfos:      file_predict_proto_msgTypes,
	}.Build()
	File_predict_proto = out.File
	file_predict_proto_goTypes = nil
	file_predict_proto_depIdxs = nil
}
