// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: graph.proto

package graphpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Metrics       map[string]float64     `protobuf:"bytes,6,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_graph_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Node) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Node) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Node) GetMetrics() map[string]float64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type Edge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Relationship  string                 `protobuf:"bytes,3,opt,name=relationship,proto3" json:"relationship,omitempty"`
	LatencyMs     float64                `protobuf:"fixed64,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	ErrorRate     float64                `protobuf:"fixed64,5,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	Throughput    float64                `protobuf:"fixed64,6,opt,name=throughput,proto3" json:"throughput,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_graph_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{1}
}

func (x *Edge) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Edge) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Edge) GetRelationship() string {
	if x != nil {
		return x.Relationship
	}
	return ""
}

func (x *Edge) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *Edge) GetErrorRate() float64 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

func (x *Edge) GetThroughput() float64 {
	if x != nil {
		return x.Throughput
	}
	return 0
}

type GraphSnapshot struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TimestampUnixNano int64                  `protobuf:"varint,1,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`
	Nodes             []*Node                `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges             []*Edge                `protobuf:"bytes,3,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GraphSnapshot) Reset() {
	*x = GraphSnapshot{}
	mi := &file_graph_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphSnapshot) ProtoMessage() {}

func (x *GraphSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphSnapshot.ProtoReflect.Descriptor instead.
func (*GraphSnapshot) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{2}
}

func (x *GraphSnapshot) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

func (x *GraphSnapshot) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *GraphSnapshot) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type StronglyConnectedComponent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ComponentId   string                 `protobuf:"bytes,1,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`
	NodeIds       []string               `protobuf:"bytes,2,rep,name=node_ids,json=nodeIds,proto3" json:"node_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StronglyConnectedComponent) Reset() {
	*x = StronglyConnectedComponent{}
	mi := &file_graph_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StronglyConnectedComponent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StronglyConnectedComponent) ProtoMessage() {}

func (x *StronglyConnectedComponent) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StronglyConnectedComponent.ProtoReflect.Descriptor instead.
func (*StronglyConnectedComponent) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{3}
}

func (x *StronglyConnectedComponent) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

func (x *StronglyConnectedComponent) GetNodeIds() []string {
	if x != nil {
		return x.NodeIds
	}
	return nil
}

type GraphRepresentation struct {
	state            protoimpl.MessageState        `protogen:"open.v1"`
	Snapshot         *GraphSnapshot                `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	TopologicalOrder []string                      `protobuf:"bytes,2,rep,name=topological_order,json=topologicalOrder,proto3" json:"topological_order,omitempty"`
	CentralityScores map[string]float64            `protobuf:"bytes,3,rep,name=centrality_scores,json=centralityScores,proto3" json:"centrality_scores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	SccComponents    []*StronglyConnectedComponent `protobuf:"bytes,4,rep,name=scc_components,json=sccComponents,proto3" json:"scc_components,omitempty"`
	FeatureTensor    []byte                        `protobuf:"bytes,5,opt,name=feature_tensor,json=featureTensor,proto3" json:"feature_tensor,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GraphRepresentation) Reset() {
	*x = GraphRepresentation{}
	mi := &file_graph_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphRepresentation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphRepresentation) ProtoMessage() {}

func (x *GraphRepresentation) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphRepresentation.ProtoReflect.Descriptor instead.
func (*GraphRepresentation) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{4}
}

func (x *GraphRepresentation) GetSnapshot() *GraphSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *GraphRepresentation) GetTopologicalOrder() []string {
	if x != nil {
		return x.TopologicalOrder
	}
	return nil
}

func (x *GraphRepresentation) GetCentralityScores() map[string]float64 {
	if x != nil {
		return x.CentralityScores
	}
	return nil
}

func (x *GraphRepresentation) GetSccComponents() []*StronglyConnectedComponent {
	if x != nil {
		return x.SccComponents
	}
	return nil
}

func (x *GraphRepresentation) GetFeatureTensor() []byte {
	if x != nil {
		return x.FeatureTensor
	}
	return nil
}

var File_graph_proto protoreflect.FileDescriptor

const file_graph_proto_rawDesc = "" +
	"\n" +
	"\vgraph.proto\x12\vaegis.graph\"\xc6\x02\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12;\n" +
	"\bmetadata\x18\x05 \x03(\v2\x1f.aegis.graph.Node.MetadataEntryR\bmetadata\x128\n" +
	"\ametrics\x18\x06 \x03(\v2\x1e.aegis.graph.Node.MetricsEntryR\ametrics\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xb8\x01\n" +
	"\x04Edge\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\"\n" +
	"\frelationship\x18\x03 \x01(\tR\frelationship\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x01R\tlatencyMs\x12\x1d\n" +
	"\n" +
	"error_rate\x18\x05 \x01(\x01R\terrorRate\x12\x1e\n" +
	"\n" +
	"throughput\x18\x06 \x01(\x01R\n" +
	"throughput\"\x91\x01\n" +
	"\rGraphSnapshot\x12.\n" +
	"\x13timestamp_unix_nano\x18\x01 \x01(\x03R\x11timestampUnixNano\x12'\n" +
	"\x05nodes\x18\x02 \x03(\v2\x11.aegis.graph.NodeR\x05nodes\x12'\n" +
	"\x05edges\x18\x03 \x03(\v2\x11.aegis.graph.EdgeR\x05edges\"Z\n" +
	"\x1aStronglyConnectedComponent\x12!\n" +
	"\fcomponent_id\x18\x01 \x01(\tR\vcomponentId\x12\x19\n" +
	"\bnode_ids\x18\x02 \x03(\tR\anodeIds\"\x9b\x03\n" +
	"\x13GraphRepresentation\x126\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x1a.aegis.graph.GraphSnapshotR\bsnapshot\x12+\n" +
	"\x11topological_order\x18\x02 \x03(\tR\x10topologicalOrder\x12c\n" +
	"\x11centrality_scores\x18\x03 \x03(\v26.aegis.graph.GraphRepresentation.CentralityScoresEntryR\x10centralityScores\x12N\n" +
	"\x0escc_components\x18\x04 \x03(\v2'.aegis.graph.StronglyConnectedComponentR\rsccComponents\x12%\n" +
	"\x0efeature_tensor\x18\x05 \x01(\fR\rfeatureTensor\x1aC\n" +
	"\x15CentralityScoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01B6Z4github.com/aegis/go-services/shared/pb/graph;graphpbb\x06proto3"

var (
	file_graph_proto_rawDescOnce sync.Once
	file_graph_proto_rawDescData []byte
)

func file_graph_proto_rawDescGZIP() []byte {
	file_graph_proto_rawDescOnce.Do(func() {
		file_graph_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_graph_proto_rawDesc), len(file_graph_proto_rawDesc)))
	})
	return file_graph_proto_rawDescData
}

var file_graph_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_graph_proto_goTypes = []any{
	(*Node)(nil),                       // 0: aegis.graph.Node
	(*Edge)(nil),                       // 1: aegis.graph.Edge
	(*GraphSnapshot)(nil),              // 2: aegis.graph.GraphSnapshot
	(*StronglyConnectedComponent)(nil), // 3: aegis.graph.StronglyConnectedComponent
	(*GraphRepresentation)(nil),        // 4: aegis.graph.GraphRepresentation
	nil,                                // 5: aegis.graph.Node.MetadataEntry
	nil,                                // 6: aegis.graph.Node.MetricsEntry
	nil,                                // 7: aegis.graph.GraphRepresentation.CentralityScoresEntry
}
var file_graph_proto_depIdxs = []int32{
	5, // 0: aegis.graph.Node.metadata:type_name -> aegis.graph.Node.MetadataEntry
	6, // 1: aegis.graph.Node.metrics:type_name -> aegis.graph.Node.MetricsEntry
	0, // 2: aegis.graph.GraphSnapshot.nodes:type_name -> aegis.graph.Node
	1, // 3: aegis.graph.GraphSnapshot.edges:type_name -> aegis.graph.Edge
	2, // 4: aegis.graph.GraphRepresentation.snapshot:type_name -> aegis.graph.GraphSnapshot
	7, // 5: aegis.graph.GraphRepresentation.centrality_scores:type_name -> aegis.graph.GraphRepresentation.CentralityScoresEntry
	3, // 6: aegis.graph.GraphRepresentation.scc_components:type_name -> aegis.graph.StronglyConnectedComponent
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_graph_proto_init() }
func file_graph_proto_init() {
	if File_graph_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_graph_proto_rawDesc), len(file_graph_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_graph_proto_goTypes,
		DependencyIndexes: file_graph_proto_depIdxs,
		MessageInfos:      file_graph_proto_msgTypes,
	}.Build()
	File_graph_proto = out.File
	file_graph_proto_goTypes = nil
	file_graph_proto_depIdxs = nil
}
